== DevOpenAPI スキル範囲について ==
DevOpenAPIへの参加にあたり、必要なスキル及び習得可能なスキルについてを明記しています。 +
当ガイドでは、まず扱う言語について説明させていただき、その後具体的にどのようなことを行っていくのか、利用するツールはどのようなものなのか、スキル獲得範囲はどの程度なのかを解説させていただきます。 +

.目次
* 第1章　言語
    - １－１：DevOpenAPIプロジェクトで取り扱う言語について
    - １－２：各言語の利用シーン
* 第2章　ツール
    - ２－１：利用するツールについての概要及び環境構築について
    - ２－２：環境構築ガイドの場所
* 第3章　要求スキル
    - ３－１：コントリビューター参加時の要求されるスキルについて
* 第4章　獲得スキル
    - ４－１：DevOpenAPI参加後身につくスキル獲得について

== 第1章　言語 ==
=== １－１：DevOpenAPIプロジェクトで取り扱う言語について ===
当プロジェクトで取り扱う言語は主に開発用の言語及びガイドや仕様書作成の際に使う言語、画面を作成するときの言語、この3つをメインの言語として取り扱います。 +
リストについては以下を参照ください。 +

.言語
* Java
* AndroidJava
* JavaScript
* HTML
* CSS
* Python
* Yaml
* AsciiDoc

また、各言語の詳細な説明については現在資料を作成中ですので完成次第アップデートしていきますのでチェックしてください。 +

=== １－２：各言語の利用シーン ===
前章（１－１：DevOpenAPIプロジェクトで取り扱う言語について）で取り上げた、メインで利用する言語の利用シーンについての解説を行います。 +
各々の特異な言語、または学習してみたい言語を選び学習し、プロジェクトに反映させていきましょう。 +

.言語利用シーン
[red]#Java# ;;
    Java言語は主にバックエンドシステムの構築に利用しています。特に、REST API作成時に利用しログイン認証APIやカレンダーAPIなどを作成する際に用います。
[red]#AndroidJava# ;;
    ネイティブのJavaとは少し異なっていますが、主にAndroid OS上で動作する言語になります。Androidアプリケーションを作成する際に利用する言語です。
[red]#JavaScript# ;;
    UIの画面制御を行いたい際に利用します。jQueryとの連携も可能で、API通信や画面に動きをつけたいときに利用します。
[red]#HTML# ;;
    UI作成をする際の基礎となる言語です。そのため、UIを作成する際は、JavaScript, HTML, CSSこの3つの言語を扱います。（利用シーンは画面作成時）
[red]#CSS# ;;
    画面に装飾を加えたいときに利用します。
[red]#Python# ;;
    現在、準備中です。
[red]#Yaml# ;;
    主に、docker-composeを作成するときや、API仕様書を作成するときに利用する言語です。
[red]#AsciiDoc# ;;
    各ガイドを作成するときに利用するマークアップ言語です。

以上が、当プロジェクトで利用する言語やその位置づけの解説になります。 +
また、解説が不十分でしたら別で各言語における詳細な説明のドキュメントも公開していますので（現在準備中）、そちらを参考に学習を進めてください。 +

== 第2章　ツール ==
=== ２－１：利用するツールについての概要及び環境構築について ===
DevOpenAPIでは様々なツールを利用します。 +
それは、エディターやIDE（統合開発環境）から各プラグイン、機能まで様々です。 +
しかし、メインで利用するツールについては主に3つだけです。それは、 +
１：eclipse +
２：Visual Studio Code +
３：docker +
この３つです。 +
また、その中でeclipse及びVSCodeの利用に関しては、利用者を選ぶので、当プロジェクトでは基本どちらのツールを利用していただいても問題ありません。 +
この2つのツールの環境構築方法は、次節の（２－２：環境構築ガイドの場所）にてリンクを掲載しますので、ご参考にしていただければ幸いです。 +

=== ２－２：環境構築ガイドの場所 ===
環境構築ガイドの参照先リンクを提供します。 +
１：link:https://github.com/Martin9420/DevOpenAPI/blob/main/SkyWayProjectGide/ProjectGide.adoc[eclipse及びベースとなる環境構築ガイドリンク] +
２：link:https://github.com/Martin9420/DevOpenAPI/blob/main/AWSCodeGuru%E5%88%A9%E7%94%A8%E3%82%AC%E3%82%A4%E3%83%89/AWSCodeGuru.adoc[AWS CodeGuru利用ガイド] +
３：VSCodeの環境構築ガイド＊現在作成中です。 +

== 第3章 要求スキル ==
=== ３－１：コントリビューター参加時の要求されるスキルについて ===
コントリビューターとして当プロジェクトに参加されるにあたり、要求されるスキルとしてはシンプルな物として設定しています。 +
例えば、基本的なPC操作ができる！などです。
プログラミングの経験がなくとも参加可能なコミュニティとして活動しているので、扱える言語が無くとも心配の必要はなく、やっているうちに言語を覚えていけば良いというスタンスです。 +

== 第4章　獲得スキル ==
=== ４－１：DevOpenAPI参加後身につくスキル獲得について ===
まず、DevOpenAPIにコントリビューターとして参加後に身につくスキルとして一番大きいものとして、プログラミング開発スキルの習得及び向上です。 +
これは、扱う言語により習得期間に若干の差が生まれてしまいますが、「動くものを素早く作成する」といった観点で開発スキルの向上が見込めます。 +
例えば、Javaの開発においては、全てのAPIを一人が作成するということはなく、１APIは一人のコントリビューターが担当する事で、深いレベルでJavaの学習が可能となります。 +
また、その他の獲得見込みスキルとしては以下になります。 +
１：SandBoxを利用したアプリケーション開発スキル +
２：Dockerコンテナを利用したアプリケーション開発スキル +
３：ユーザインタフェースのデザインスキル習得及び向上 +
４：サーバインフラ構成スキル +
５：スマートフォンアプリケーションの開発スキル +
などなど....
以上が、当プロジェクトに参加した際のスキル獲得エリアとなります。 +
また、その他にも要望に応じて様々な言語及びツールを利用していきますので是非ご提案をよろしくお願いいたします。 +





